### ISSUE TITLE
YELLOW hard to see

### ISSUE THREAD

**Issue by nelsobe** [byu-cpe/pygrader#1]
On my Mac YELLOW is pretty light, hard to see in a normal terminal window.  

Could we make the color for where you input scores something more bright (like RED) since that is the important part of the program?

I modified it locally but was not sure if I was going to mistakenly push that to the repo when I did pushes to my own class grading repo (I am showing my ignorance here)...   Plus, dumb to have a fork just over a color...

Thanks.

**Comment by jgoeders** [comment]
I try to save RED for errors.  How about PURPLE, BLUE or GREEN?

**Comment by nelsobe** [comment]
Anything that is more readable than YELLOW would be OK...

**Comment by jgoeders** [comment]
Fixed in 85a1fd72c5cd44fd02d1fcfdec2a7e4206869ad8
